name: Firebase Hosting CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build

      - name: Deploy preview (PR)
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_APEX_AUTOMOTIVE_9078E }}"
          projectId: apex-automotive-9078e
          channelId: pr-${{ github.event.pull_request.number }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Deploy to production (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_APEX_AUTOMOTIVE_9078E }}"
          projectId: apex-automotive-9078e
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
